nelmio_cors:
    defaults:
        allow_credentials: true
        allow_origin: []
        allow_headers: []
        allow_methods: []
        allow_private_network: false
        expose_headers: ['Access-Control-Allow-Origin']
        max_age: 0
        hosts: []
        origin_regex: false
        forced_allow_origin_value: ~
        skip_same_as_origin: true
    paths:
        '^/api/':
            allow_origin: ['*']
            allow_headers: ['*']
            allow_credentials: true
            allow_methods: ['POST', 'PUT', 'GET', 'DELETE', 'OPTION']
            max_age: 3600
        '^/':
            allow_origin: ['*']
            allow_headers: ['*']
            allow_credentials: true
            allow_methods: ['POST', 'PUT', 'GET', 'DELETE', 'OPTION']
            max_age: 3600
            hosts: ['^api\.']