controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

api_login:
    path: /api/login
    controller: App\Controller\SecurityController::login
api_login_check:
    path: /api/login_check
